### ISSUE TITLE
Sub-minute test times cause labels to be unreadable

### ISSUE THREAD

**Issue by colindean** [scribu/travis-stats#10]
Able to reproduce on https://scribu.github.io/travis-stats/#pittmesh/pittmesh.net

![screen shot 2016-08-11 at 13 15 57](https://cloud.githubusercontent.com/assets/197224/17597868/c75cafb0-5fc5-11e6-9107-6f7e29e5c52b.png)

**Comment by scribu** [comment]
Right. Guess numbers like 0.6000000000000001 should be averaged to 0.6.
