### ISSUE TITLE
Rendering looks broken for nexB/scancode-toolkit

### ISSUE THREAD

**Issue by sschuberth** [scribu/travis-stats#12]
While looking at http://scribu.github.io/travis-stats/#nexB/scancode-toolkit I find the rendering broken (tested with both Firefox and Chrome on Windows):

![2016-11-25_162540](https://cloud.githubusercontent.com/assets/349154/20629429/d7eda1cc-b32b-11e6-8d32-e89f01fb9509.jpg)

It looks like both data is missing, and numbers are rendered overlapped.

**Comment by scribu** [comment]
I just pushed a fix for the overlapped numbers.

Regarding missing data:

* we only make 20 API requests to Travis CI, so old builds could be missing
* we only display builds made against the `master` branch.

**Comment by sschuberth** [comment]
Thanks for the fix. Regarding the branch, if you currently only support one single branch, how about not hard-coding that to `master` but using what ever is the default branch? At the example of the nexB/scancode-toolkit project that would be the `develop` branch.

**Comment by scribu** [comment]
Yeah, I'm going to fix that as part of #11.
