### ISSUE TITLE
Unable to hit Travis Enterprise locally

### ISSUE THREAD

**Issue by colindean** [scribu/travis-stats#8]
Hitting the CORS problem:

```
d3.v4.min.js:3 

XMLHttpRequest cannot load file:///Users/cdean/Source/travis-stats/config.json. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https, chrome-extension-resource.

send @ d3.v4.min.js:3
```

Is there a way to avoid CORS problems on `file://` urls for development? Or am I going to have to set up a simple server, e.g. `python -m SimpleHTTPServer`, in order to do development?

**Comment by scribu** [comment]
If you can make `getConfigUrl()` return something that works when index.html is loaded via `file://`, great.

Otherwise, yeah, `SimpleHTTPServer` is the way to go.
